### ISSUE TITLE
How did you generate the /odometry/filteded data?

### ISSUE THREAD

**Issue by soulslicer** [umass-amrl/vision_slam_frontend#3]
I currently have stereo data, but clearly the `/odometry/filteded` is useful in the pose graph. What sensor / module did you use to generate this? Isn't an IMU only providing angular velocity and acceleration via `/sensor_msgs/Imu`? How do you generate `nav_msgs/Odometry` from that?

**Comment by TheCynosure** [comment]
Odometry is something that you gather from your wheels motor encoders. Usually this should be given to you through a driver by whoever made your robot. But, if you are using something custom or don't have access to it here is a paper about how to derive it from motor ticks: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-186-mobile-autonomous-systems-laboratory-january-iap-2005/study-materials/odomtutorial.pdf.

I am by no means an expert on odometry, but feel free to follow up on this with questions (and re-open the issue).
